---
- name: Download microsoft product repository
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
    dest: /tmp/packages-microsoft-prod.deb
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "20.04"

- name: Install microsoft product repository
  apt:
    deb: /tmp/packages-microsoft-prod.deb
    update_cache: yes
  become: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "20.04"

- name: Install .net core sdk
  apt:
    name: dotnet-sdk-6.0
    state: present
    force: yes
    update_cache: yes
  become: true

- name: Create kestrel.service configuration
  template:
    src: files/kestrel.service
    dest: "{{ env.conf_path }}/kestrel.service"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
