---
- name: Install common dependencies
  become: true
  ansible.builtin.apt:
    pkg:
      - curl
      - wget
      - zip
      - unzip
      - net-tools
      - network-manager
      - software-properties-common
      - apt-transport-https
    state: present
    force: true
    update_cache: true

- name: Ensures application folder directory exists
  become: true
  ansible.builtin.file:
    path: "{{ env.root_path }}"
    owner: www-data
    group: www-data
    mode: "0650"
    state: directory

- name: Ensures config folder directory exists
  become: true
  ansible.builtin.file:
    path: "{{ env.conf_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0650"
    state: directory
