---
- name: Install ruby 2.0
  become: true
  ansible.builtin.apt:
    pkg:
      - wget
      - ruby-full
    state: present
    force: true
    update_cache: true

- name: Check that CodeDeploy is installed
  ansible.builtin.stat:
    path: /opt/codedeploy-agent
  register: code_deploy_installed

- name: Download CodeDeploy
  ansible.builtin.get_url:
    url: "https://{{ env.bucket_name }}.s3.{{ env.region_identifier }}.amazonaws.com/latest/install"
    dest: "/home/{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0775"
  when: not code_deploy_installed.stat.exists

- name: Install CodeDeploy
  become: true
  ansible.builtin.command: "/home/{{ ansible_user }}/install auto"
  when: not code_deploy_installed.stat.exists
  changed_when: code_deploy_installed.stat.exists

- name: Remove CodeDeploy installer
  ansible.builtin.file:
    dest: "/home/{{ ansible_user }}/install"
    state: absent
  when: not code_deploy_installed.stat.exists
