---
- name: Install nginx
  become: true
  ansible.builtin.apt:
    pkg:
      - nginx
    state: present
    update_cache: true

- name: Disable default config
  become: true
  ansible.builtin.file:
    dest: /etc/nginx/sites-enabled/default
    state: absent

- name: Create nginx.conf configuration
  become: true
  ansible.builtin.template:
    src: files/nginx.conf
    dest: "{{ env.conf_path }}/nginx.conf"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Create a symbolic link
  become: true
  ansible.builtin.file:
    src: "{{ env.conf_path }}/nginx.conf"
    dest: /etc/nginx/sites-enabled/{{ env.project_name }}.conf
    state: link

- name: Add www-data group to vagrant user
  become: true
  ansible.builtin.user:
    name: vagrant
    groups: www-data
    append: true

- name: Start and enable nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Reload nginx config
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
