---
- name: Install nginx
  become: yes
  apt:
    pkg:
      - nginx
    state: latest
    update_cache: yes

- name: Disable default config
  become: yes
  file: 
    dest: /etc/nginx/sites-enabled/default 
    state: absent

- name: Create nginx.conf configuration
  become: yes
  template:
    src: files/nginx.conf
    dest: "{{ env.conf_path }}/nginx.conf"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Start and enable nginx
  become: yes
  service:
    name: nginx
    state: started
    enabled: yes
