---
- name: Install common dependencies
  apt:
    pkg:
      - curl
      - wget
      - zip
      - unzip
      - net-tools
      - network-manager
      - software-properties-common
      - apt-transport-https
    state: present
    force: yes
    update_cache: yes

- name: Ensures application folder directory exists
  file:
    path: "{{ env.root_path }}"
    owner: www-data
    group: www-data
    state: directory

- name: Ensures config folder directory exists
  file:
    path: "{{ env.conf_path }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
