all:
  hosts:
    dotnet:
      ansible_host: localhost
  vars:
    ansible_user: ubuntu
    ansible_become: yes
    ansible_connection: ssh
    ansible_become_method: sudo
    ansible_ssh_pipelining: true
    ansible_python_interpreter: /usr/bin/python3
    env:
      app_env: Development
      telemetry_message: true
      project_name: <project-name>
      conf_path: <conf-path>
      root_path: <root-path>
      bucket_name: <bucket_name>
      region_identifier: <region_identifier>
